name: 'Generate Auto Changelog'

on:
  push:
    branches:
      - main

jobs:
  Changelog:
    runs-on: ubuntu-latest
    steps:
      # checkout resp
      - uses: actions/checkout@v2

      # Set git user
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Actions"

      # Generate changelog
      - uses: nuuday/github-changelog-action@v1.0.0
        with:
          next_version: "TBD"

      # Add Changelog
      - uses: github-actions-x/commit@v2.8
        with:
          github-token: ${{ secrets.NFANGXU_GITHUB_TOKEN }}
          push-branch: auto-changelog
          files: CHANGELOG.md
          commit-message: 'auto changelog'
          rebase: 'true'

      # Create pull request
      - uses: repo-sync/pull-request@v2
        with:
          source_branch: auto-changelog
          destination_branch: "main"
          pr_title: "Update Changelog"
          github_token: ${{ secrets.NFANGXU_GITHUB_TOKEN }}
