name: 'Generate Auto Changelog'

on:
  push:
    branches:
      - main

jobs:
  Changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Change branch
        run: |-
          git checkout -b automatic-changelog && git checkout automatic-changelog

      - name: Generate Changelog
        uses: nuuday/github-changelog-action@v1.0.0
        with:
          next_version: "TBD"

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'automatic changelog'
          branch: automatic-changelog
          push_options: '--force'

      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: automatic-changelog
          destination_branch: "main"
          pr_title: "Update Changelog"
          github_token: ${{ secrets.NFANGXU_GITHUB_TOKEN }}
