name: 'Generate Auto Changelog'

on:
  push:
    branches:
      - main

jobs:
  Changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Changelog
        uses: nuuday/github-changelog-action@v1.0.1
        with:
          next_version: "TBD"

      - name: Change branch
        run: |-
          git checkout -b changelog-bot || git checkout changelog-bot

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update changelog
          branch: changelog-bot
          push_options: '--force'

      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: changelog-bot
          destination_branch: "main"
          pr_title: Changelog
          github_token: ${{ secrets.NFANGXU_GITHUB_TOKEN }}
