name: 'Generate Auto Changelog'

on:
  push:
    branches:
      - main

jobs:
  Changelog:
    runs-on: ubuntu-latest
    steps:
      # checkout resp
      - uses: actions/checkout@v2

      # Set git user
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Actions"

      # Generate changelog
      - uses: nuuday/github-changelog-action@v1.0.0
        with:
          next_version: "TBD"

      # Add Changelog
      - run: |
          git checkout -b changelog-${GITHUB_SHA}
          git add CHANGELOG.md
          git commit -m "chore: auto update changelog" CHANGELOG.md
          cat CHANGELOG.md

      # Create pull request
      - uses: repo-sync/pull-request@v2
        with:
          source_branch: changelog-${{ GITHUB_SHA }}
          destination_branch: "main"
          pr_title: "Update Changelog"
          github_token: ${{ secrets.NFANGXU_GITHUB_TOKEN }}
