name: 'Generate Auto Changelog'

on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: nuuday/github-changelog-action@v1.0.0
        with:
          next_version: "TBD"
